---
- hosts: all
  sudo: true
  tasks:
  - name: Add maven repository
    apt_repository: repo='ppa:andrei-pozolotin/maven3' state=present
  - name: Add postgresql repository
    apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ trusty-pgdg main' state=present
  - name: Add postgresql repository key
    apt_key: url=https://www.postgresql.org/media/keys/ACCC4CF8.asc state=present
  - name: Copy .bash_profile
    template: src=templates/bash_profile.conf.j2 dest=/home/vagrant/.bash_profile
  - name: Add PostGIS repository key
    apt_key: keyserver=keyserver.ubuntu.com id=6B827C12C2D425E227EDCA75089EBE08314DF160
  - name: Add PostGIS repository
    apt_repository: repo='deb http://ppa.launchpad.net/ubuntugis/ppa/ubuntu devel main' state=present
  - name: apt-get update
    apt: update_cache=yes
  - name: Install GIT
    apt: name=git state=present
  - name: Install NGINX
    apt: name=nginx state=present
  - name: Install Maven
    apt: name=maven3 state=present
  - name: Install PostgreSQL 9.4+
    apt: name=postgresql-9.4 state=present
  - name: Install PostGIS
    apt: name=postgresql-9.4-postgis-2.1 state=present force=yes
  - name: Install PostGIS scripts
    apt: name=postgresql-9.4-postgis-2.1-scripts state=present force=yes
  - name: Trust local connections to PostgresSQL
    template: src=templates/pg_hba.conf.j2 dest=/etc/postgresql/9.4/main/pg_hba.conf
  - name: Make PostgreSQL listen on all interfaces
    template: src=templates/postgresql.conf.j2 dest=/etc/postgresql/9.4/main/postgresql.conf
  - name: restart postgres
    service: name=postgresql state=restarted
  - name: Configure NGINX
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
  - name: Restart NGINX
    service: name=nginx state=restarted
  - name: Create working directory
    file: path=/harja state=directory mode=0777
  - name: Copy Deus private key
    copy: src=keys/id_rsa_harjavagrant dest=/harja/id_rsa_harjavagrant
  - name: Checkout harja-tietokanta
    sudo: yes
    sudo_user: postgres
    git: repo=deveo@deus.solita.fi:Solita/projects/harja/repositories/git/harja-tietokanta
         dest=/harja/checkout
         version=develop
         key_file=/harja/id_rsa_harjavagrant
         accept_hostkey=yes
  - name: Install database template
    command: sh kanta_template.sh
    sudo: yes
    sudo_user: postgres
    args:
       chdir: /harja/checkout
  - name: Install test database template
    command: sh testikanta_template.sh
    sudo: yes
    sudo_user: postgres
    args:
       chdir: /harja/checkout
  - name: Install database
    command: sh kanta_uusiksi.sh
    sudo: yes
    sudo_user: postgres
    args:
       chdir: /harja/checkout
  - name: Install test database
    command: sh testikanta_uusiksi.sh
    sudo: yes
    sudo_user: postgres
    args:
       chdir: /harja/checkout
