---
- hosts: all
  sudo: yes
  tasks:
    - name: Varmistetaan, ett채 Harjan sovellushakemisto on olemassa
      file: path=/opt/harja state=directory owner=harja group=harja mode="u=rwx,g=rwx,o=rx"
      
    - name: kirjoita serviced konfiguraatio
      template: src=templates/centos7-service-template.j2 dest=/etc/systemd/system/harja.service mode=755
      with_items:
        - description: "Harja testiymparisto"
          start_file: /opt/harja/harja.sh
          user_name: harja
          user_group: harja
          workingdir: /opt/harja

    - name: pysayta harja
      service: name=harja state=stopped
      when: '{{harja_migrate_only}} == false'

    - name: tuhoa kanta
      sudo: yes
      sudo_user: postgres
      postgresql_db: name=harja state=absent
      when: '{{harja_migrate_only}} == false'

    - name: luo kanta
      sudo: yes
      sudo_user: postgres
      postgresql_db: name=harja owner=harja state=present

    - name: tee postgis-extensio
      sudo: yes
      sudo_user: postgres
      postgresql_ext: db=harja name=postgis state=present

    - name: poista entiset siirretyt migraatioskriptit palvelimelta
      file: path=/opt/harja/tietokanta state=absent
      
    - name: kopioi tietokantamigraatiot
      unarchive: src=../../tietokanta.tgz dest=/opt/harja owner=harja group=harja

    - name: aja tietokantamigraatiot
      command: mvn compile flyway:migrate -Dflyway.password=harja123
      args:
        chdir: /opt/harja/tietokanta

    - name: dumppaa testidata
      sudo: yes
      sudo_user: harja
      shell: psql -p5432 harja -X -q -a -l -v ON_ERROR_STOP=1 --pset pager=off -f testidata.sql > /dev/null
      args:
        chdir: /opt/harja/tietokanta
      when: '{{harja_migrate_only}} == false'

    - name: Kopioi viimeisin Harja jar
      copy: src=../../target/harja-0.0.1-SNAPSHOT-standalone.jar dest=/opt/harja/harja-nightly.jar
        
    - name: Kopioi sovelluksen konfiguraatio
      template: src=templates/asetukset_dev.edn dest=/opt/harja/asetukset.edn

    - name: Kopioi k채ynnistysskripti
      template: src=templates/harja.sh dest=/opt/harja/harja.sh mode=755

    - name: K채ynnist채 Harja
      sudo: yes
      service: name=harja state=restarted
      register: start

      

    
  