---
- hosts: all
  roles:
    - role-epel
  sudo: yes
  tasks:
    - name: install nginx repo rpm
      yum:
        name: http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm
    - name: install postgresql repo rpm
      yum:
        name: http://yum.postgresql.org/9.4/redhat/rhel-7-x86_64/pgdg-centos94-9.4-1.noarch.rpm
    - name: install nginx
      yum: pkg=nginx update_cache=yes state=latest
    - name: install postgresql
      yum: pkg=postgresql94-server state=latest
    - name: install postgis
      yum: pkg=postgis2_94.x86_64 state=latest
    - name: install maven 3
      yum: pkg=maven.noarch state=latest
    - name: install java 8
      yum: pkg=java-1.8.0-openjdk-devel.x86_64 state=latest
    - name: update javac alternatives
      alternatives: name=javac link=/usr/bin/javac path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.60-2.b27.el7_1.x86_64/bin/javac
    - name: update java alternatives
      alternatives: name=java link=/usr/bin/java path=/usr/lib/jvm/java-1.8.0-openjdk-1.8.0.60-2.b27.el7_1.x86_64/jre/bin/java
  handlers:
    - name: restart nginx
      service: name=nginx state=restarted
    - name: restart postgres
      service: name=postgres state=restarted
